language: julia
os:
    - linux
julia:
    - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
after_success:
    # push coverage results to Codecov
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'