language: julia
os:
    - linux
julia:
    - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
after_success:
    # push coverage results to Codecov
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("StateSpaceModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia -e 'import Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip